const mysql = require('mysql2/promise');
const dotenv = require('dotenv');
dotenv.config();

const categoriesData = [
  {
    id: 12, name: 'Meat & Fish', icon: 'Drumstick',
    image: '/images/meat.png',
    brands: ['Local'],
    items: [
      { name: 'Whole Chicken (Skinless)', sub: 'Chicken' },
      { name: 'Whole Chicken (With Skin)', sub: 'Chicken' },
      { name: 'Country Chicken (Natu Kodi)', sub: 'Chicken' },
      { name: 'Organic Country Chicken', sub: 'Chicken' },
      { name: 'Chicken Curry Cut', sub: 'Chicken' },
      { name: 'Chicken Boneless', sub: 'Chicken' },
      { name: 'Chicken Breast', sub: 'Chicken' },
      { name: 'Chicken Thigh', sub: 'Chicken' },
      { name: 'Chicken Drumsticks', sub: 'Chicken' },
      { name: 'Chicken Wings', sub: 'Chicken' },
      { name: 'Chicken Leg Piece', sub: 'Chicken' },
      { name: 'Chicken Liver', sub: 'Chicken' },
      { name: 'Chicken Gizzard', sub: 'Chicken' },
      { name: 'Chicken Neck', sub: 'Chicken' },
      { name: 'Chicken Mince (Keema)', sub: 'Chicken' },
      { name: 'Mutton Curry Cut', sub: 'Mutton' },
      { name: 'Boneless Mutton', sub: 'Mutton' },
      { name: 'Mutton Keema', sub: 'Mutton' },
      { name: 'Mutton Liver', sub: 'Mutton' },
      { name: 'Mutton Kidney', sub: 'Mutton' },
      { name: 'Mutton Heart', sub: 'Mutton' },
      { name: 'Mutton Brain', sub: 'Mutton' },
      { name: 'Mutton Leg', sub: 'Mutton' },
      { name: 'Mutton Ribs', sub: 'Mutton' },
      { name: 'Whole Duck', sub: 'Duck' },
      { name: 'Duck Curry Cut', sub: 'Duck' },
      { name: 'Rohu', sub: 'Fish' },
      { name: 'Katla', sub: 'Fish' },
      { name: 'Mrigal', sub: 'Fish' },
      { name: 'Tilapia', sub: 'Fish' },
      { name: 'Common Carp', sub: 'Fish' },
      { name: 'Grass Carp', sub: 'Fish' },
      { name: 'Silver Carp', sub: 'Fish' },
      { name: 'Seer Fish (Vanjaram)', sub: 'Fish' },
      { name: 'Pomfret White', sub: 'Fish' },
      { name: 'Pomfret Black', sub: 'Fish' },
      { name: 'King Fish', sub: 'Fish' },
      { name: 'Sardine', sub: 'Fish' },
      { name: 'Mackerel (Bangda)', sub: 'Fish' },
      { name: 'Tuna', sub: 'Fish' },
      { name: 'Anchovy', sub: 'Fish' },
      { name: 'Ribbon Fish', sub: 'Fish' },
      { name: 'Small Prawns', sub: 'Prawn' },
      { name: 'Medium Prawns', sub: 'Prawn' },
      { name: 'Jumbo Prawns', sub: 'Prawn' },
      { name: 'Freshwater Prawns', sub: 'Prawn' },
      { name: 'Fresh Crab', sub: 'Crab' },
      { name: 'Mud Crab', sub: 'Crab' },
      { name: 'Squid Rings', sub: 'Squid' },
      { name: 'Whole Squid', sub: 'Squid' },
      { name: 'Cuttlefish', sub: 'Squid' },
      { name: 'Lobster', sub: 'Shellfish' },
      { name: 'Clams', sub: 'Shellfish' },
      { name: 'Mussels', sub: 'Shellfish' },
    ]
  },
  {
    id: 13, name: 'Cleaning Essentials', icon: 'SprayCan',
    image: '/images/cleaning.png',
    brands: ['Surf Excel', 'Ariel', 'Tide', 'Rin', 'Wheel', 'Ghadi', 'Henko', 'Vim', 'Exo', 'Pril', 'Harpic', 'Lizol', 'Domex', 'Colin', 'Good Knight', 'All Out', 'HIT', 'Baygon', 'Mortein', 'Local'],
    items: [
      { name: 'Surf Excel Easy Wash', sub: 'Powder' },
      { name: 'Surf Excel Matic Front Load', sub: 'Powder' },
      { name: 'Surf Excel Matic Top Load', sub: 'Powder' },
      { name: 'Ariel Complete', sub: 'Powder' },
      { name: 'Ariel Matic Front Load', sub: 'Powder' },
      { name: 'Ariel Matic Top Load', sub: 'Powder' },
      { name: 'Tide Plus', sub: 'Powder' },
      { name: 'Tide Naturals', sub: 'Powder' },
      { name: 'Rin Detergent Powder', sub: 'Powder' },
      { name: 'Wheel Active', sub: 'Powder' },
      { name: 'Wheel Green', sub: 'Powder' },
      { name: 'Ghadi Detergent Powder', sub: 'Powder' },
      { name: 'Henko Detergent Powder', sub: 'Powder' },
      { name: 'Mr. White Detergent Powder', sub: 'Powder' },
      { name: 'Surf Excel Liquid', sub: 'Liquid' },
      { name: 'Ariel Liquid', sub: 'Liquid' },
      { name: 'Genteel Liquid', sub: 'Liquid' },
      { name: 'Godrej Ezee Liquid', sub: 'Liquid' },
      { name: 'IFB Essentials Liquid', sub: 'Liquid' },
      { name: 'Rin Bar', sub: 'Bar' },
      { name: 'Wheel Bar', sub: 'Bar' },
      { name: 'Tide Bar', sub: 'Bar' },
      { name: 'Ghadi Bar', sub: 'Bar' },
      { name: '501 Washing Bar', sub: 'Bar' },
      { name: 'Local Washing Soap', sub: 'Bar' },
      { name: 'Vim Dishwash Bar', sub: 'Bar' },
      { name: 'Exo Dishwash Bar', sub: 'Bar' },
      { name: 'Pril Dishwash Bar', sub: 'Bar' },
      { name: 'Local Dishwash Bar', sub: 'Bar' },
      { name: 'Vim Liquid', sub: 'Liquid' },
      { name: 'Exo Liquid', sub: 'Liquid' },
      { name: 'Pril Liquid', sub: 'Liquid' },
      { name: 'Fortune Dishwash Liquid', sub: 'Liquid' },
      { name: 'Steel Scrubber', sub: 'Tool' },
      { name: 'Sponge Scrubber', sub: 'Tool' },
      { name: 'Scotch-Brite Scrub Pad', sub: 'Tool' },
      { name: 'Coconut Scrubber', sub: 'Tool' },
      { name: 'Bottle Cleaning Brush', sub: 'Tool' },
      { name: 'Dish Cleaning Brush', sub: 'Tool' },
      { name: 'Sink Brush', sub: 'Tool' },
      { name: 'Harpic Original', sub: 'Cleaner' },
      { name: 'Harpic Power Plus', sub: 'Cleaner' },
      { name: 'Domex Toilet Cleaner', sub: 'Cleaner' },
      { name: 'Lysol Toilet Cleaner', sub: 'Cleaner' },
      { name: 'Lizol Citrus', sub: 'Cleaner' },
      { name: 'Lizol Lavender', sub: 'Cleaner' },
      { name: 'Lizol Floral', sub: 'Cleaner' },
      { name: 'Domex Floor Cleaner', sub: 'Cleaner' },
      { name: 'Herbal Floor Cleaner', sub: 'Cleaner' },
      { name: 'Phenyl White', sub: 'Cleaner' },
      { name: 'Phenyl Black', sub: 'Cleaner' },
      { name: 'Colin Glass Cleaner', sub: 'Cleaner' },
      { name: 'Colin Refill', sub: 'Cleaner' },
      { name: 'Herbal Glass Cleaner', sub: 'Cleaner' },
      { name: 'Colin Multi Surface Cleaner', sub: 'Cleaner' },
      { name: 'Cif Surface Cleaner', sub: 'Cleaner' },
      { name: 'Herbal Surface Cleaner', sub: 'Cleaner' },
      { name: 'Dettol Disinfectant Liquid', sub: 'Cleaner' },
      { name: 'Savlon Disinfectant', sub: 'Cleaner' },
      { name: 'Dettol Antiseptic Liquid', sub: 'Cleaner' },
      { name: 'Floor Mop', sub: 'Tool' },
      { name: 'Spin Mop', sub: 'Tool' },
      { name: 'Bucket Mop Set', sub: 'Tool' },
      { name: 'Cotton Mop', sub: 'Tool' },
      { name: 'Floor Wiper', sub: 'Tool' },
      { name: 'Toilet Brush', sub: 'Tool' },
      { name: 'Long Handle Brush', sub: 'Tool' },
      { name: 'Hand Brush', sub: 'Tool' },
      { name: 'Dust Pan', sub: 'Tool' },
      { name: 'Broom (Grass)', sub: 'Tool' },
      { name: 'Plastic Broom', sub: 'Tool' },
      { name: 'Coconut Broom', sub: 'Tool' },
      { name: 'Small Garbage Bags', sub: 'Bag' },
      { name: 'Medium Garbage Bags', sub: 'Bag' },
      { name: 'Large Garbage Bags', sub: 'Bag' },
      { name: 'Biodegradable Garbage Bags', sub: 'Bag' },
      { name: 'Rubber Gloves', sub: 'Glove' },
      { name: 'Disposable Gloves', sub: 'Glove' },
      { name: 'Heavy Duty Cleaning Gloves', sub: 'Glove' },
      { name: 'Good Knight Liquid Refill', sub: 'Pest' },
      { name: 'Good Knight Machine', sub: 'Pest' },
      { name: 'All Out Liquid Refill', sub: 'Pest' },
      { name: 'All Out Machine', sub: 'Pest' },
      { name: 'Mortein Liquid', sub: 'Pest' },
      { name: 'Mortein Coil', sub: 'Pest' },
      { name: 'Good Knight Coil', sub: 'Pest' },
      { name: 'HIT Mosquito Spray', sub: 'Pest' },
      { name: 'HIT Cockroach Spray', sub: 'Pest' },
      { name: 'Baygon Spray', sub: 'Pest' },
      { name: 'Cockroach Gel', sub: 'Pest' },
      { name: 'Ant Powder', sub: 'Pest' },
      { name: 'Rat Glue Pad', sub: 'Pest' },
      { name: 'Rat Trap', sub: 'Pest' },
      { name: 'Rat Poison', sub: 'Pest' },
      { name: 'Comfort Fabric Conditioner', sub: 'Liquid' },
      { name: 'Genteel Fabric Conditioner', sub: 'Liquid' },
      { name: 'Stain Remover', sub: 'Liquid' },
      { name: 'Fabric Whitener', sub: 'Liquid' },
      { name: 'Ujala Fabric Whitener', sub: 'Liquid' },
      { name: 'Bleaching Powder', sub: 'Powder' },
      { name: 'Washing Soda', sub: 'Powder' },
      { name: 'Caustic Soda', sub: 'Powder' },
      { name: 'Toilet Acid', sub: 'Cleaner' }
    ]
  },
  {
    id: 14, name: 'Personal Care', icon: 'Heart',
    image: '/images/personal.png',
    brands: ['Lux', 'Dove', 'Lifebuoy', 'Santoor', 'Cinthol', 'Dettol', 'Pears', 'Hamam', 'Medimix', 'Clinic Plus', 'Sunsilk', 'Pantene', 'Head & Shoulders', 'Tresemmé', 'Meera', 'Colgate', 'Pepsodent', 'Closeup', 'Sensodyne', 'Gillette', 'Park Avenue', 'Old Spice', "Pond's", 'Nivea', 'Himalaya', 'Vaseline', 'Garnier', 'Local'],
    items: [
      { name: 'Lux Jasmine Soap', sub: 'Soap' },
      { name: 'Lux Rose Soap', sub: 'Soap' },
      { name: 'Lux Sandal Soap', sub: 'Soap' },
      { name: 'Dove Cream Beauty Bathing Bar', sub: 'Soap' },
      { name: 'Dove Sensitive Skin Soap', sub: 'Soap' },
      { name: 'Lifebuoy Total', sub: 'Soap' },
      { name: 'Lifebuoy Lemon Fresh', sub: 'Soap' },
      { name: 'Lifebuoy Care', sub: 'Soap' },
      { name: 'Santoor Sandal & Turmeric', sub: 'Soap' },
      { name: 'Santoor Aloe Vera', sub: 'Soap' },
      { name: 'Cinthol Original', sub: 'Soap' },
      { name: 'Cinthol Lime', sub: 'Soap' },
      { name: 'Cinthol Cool', sub: 'Soap' },
      { name: 'Dettol Original Soap', sub: 'Soap' },
      { name: 'Dettol Skincare Soap', sub: 'Soap' },
      { name: 'Pears Pure & Gentle', sub: 'Soap' },
      { name: 'Pears Oil Clear', sub: 'Soap' },
      { name: 'Medimix Ayurvedic Soap', sub: 'Soap' },
      { name: 'Mysore Sandal Soap', sub: 'Soap' },
      { name: 'Hamam Neem Soap', sub: 'Soap' },
      { name: 'Patanjali Neem Soap', sub: 'Soap' },
      { name: 'Patanjali Aloe Vera Soap', sub: 'Soap' },
      { name: 'Dove Body Wash', sub: 'Soap' },
      { name: 'Lux Body Wash', sub: 'Soap' },
      { name: 'Pears Body Wash', sub: 'Soap' },
      { name: 'Nivea Body Wash', sub: 'Soap' },
      { name: 'Fiama Body Wash', sub: 'Soap' },
      { name: 'Clinic Plus Strong & Long', sub: 'Shampoo' },
      { name: 'Sunsilk Black Shine', sub: 'Shampoo' },
      { name: 'Sunsilk Thick & Long', sub: 'Shampoo' },
      { name: 'Dove Hair Fall Rescue', sub: 'Shampoo' },
      { name: 'Dove Intense Repair', sub: 'Shampoo' },
      { name: 'Pantene Hair Fall Control', sub: 'Shampoo' },
      { name: 'Pantene Silky Smooth', sub: 'Shampoo' },
      { name: 'Head & Shoulders Cool Menthol', sub: 'Shampoo' },
      { name: 'Head & Shoulders Smooth & Silky', sub: 'Shampoo' },
      { name: 'Head & Shoulders Anti Hair Fall', sub: 'Shampoo' },
      { name: 'Tresemmé Keratin Smooth', sub: 'Shampoo' },
      { name: 'Tresemmé Hair Fall Defense', sub: 'Shampoo' },
      { name: 'Meera Herbal Shampoo', sub: 'Shampoo' },
      { name: 'Patanjali Kesh Kanti Shampoo', sub: 'Shampoo' },
      { name: 'Himalaya Anti Hair Fall Shampoo', sub: 'Shampoo' },
      { name: 'Dove Conditioner', sub: 'Shampoo' },
      { name: 'Pantene Conditioner', sub: 'Shampoo' },
      { name: 'Tresemmé Conditioner', sub: 'Shampoo' },
      { name: 'Sunsilk Conditioner', sub: 'Shampoo' },
      { name: 'Himalaya Conditioner', sub: 'Shampoo' },
      { name: 'Parachute Coconut Oil', sub: 'Oil' },
      { name: 'Dabur Amla Hair Oil', sub: 'Oil' },
      { name: 'Indulekha Hair Oil', sub: 'Oil' },
      { name: 'Navratna Hair Oil', sub: 'Oil' },
      { name: 'Bajaj Almond Drops', sub: 'Oil' },
      { name: 'Kesh King Hair Oil', sub: 'Oil' },
      { name: 'Himalaya Hair Oil', sub: 'Oil' },
      { name: 'Patanjali Hair Oil', sub: 'Oil' },
      { name: 'Colgate Strong Teeth', sub: 'Paste' },
      { name: 'Colgate Active Salt', sub: 'Paste' },
      { name: 'Colgate Max Fresh', sub: 'Paste' },
      { name: 'Pepsodent Germicheck', sub: 'Paste' },
      { name: 'Closeup Red Hot', sub: 'Paste' },
      { name: 'Dabur Red Toothpaste', sub: 'Paste' },
      { name: 'Sensodyne', sub: 'Paste' },
      { name: 'Himalaya Complete Care', sub: 'Paste' },
      { name: 'Patanjali Dant Kanti', sub: 'Paste' },
      { name: 'Colgate Toothbrush', sub: 'Brush' },
      { name: 'Oral-B Toothbrush', sub: 'Brush' },
      { name: 'Pepsodent Toothbrush', sub: 'Brush' },
      { name: 'Sensodyne Toothbrush', sub: 'Brush' },
      { name: 'Kids Toothbrush', sub: 'Brush' },
      { name: 'Listerine Cool Mint', sub: 'Paste' },
      { name: 'Colgate Mouthwash', sub: 'Paste' },
      { name: 'Oral-B Mouthwash', sub: 'Paste' },
      { name: 'Himalaya Mouthwash', sub: 'Paste' },
      { name: 'Gillette Shaving Cream', sub: 'Shave' },
      { name: 'Old Spice Shaving Cream', sub: 'Shave' },
      { name: 'Park Avenue Shaving Cream', sub: 'Shave' },
      { name: 'Gillette Mach3', sub: 'Shave' },
      { name: 'Gillette Guard', sub: 'Shave' },
      { name: 'SuperMax Razor', sub: 'Shave' },
      { name: 'Gillette Blades', sub: 'Shave' },
      { name: 'SuperMax Blades', sub: 'Shave' },
      { name: 'Old Spice After Shave', sub: 'Shave' },
      { name: 'Park Avenue After Shave', sub: 'Shave' },
      { name: 'Gillette After Shave Gel', sub: 'Shave' },
      { name: 'Himalaya Neem Face Wash', sub: 'Skin' },
      { name: 'Garnier Face Wash', sub: 'Skin' },
      { name: "Pond's Face Wash", sub: 'Skin' },
      { name: 'Clean & Clear Face Wash', sub: 'Skin' },
      { name: 'Nivea Face Wash', sub: 'Skin' },
      { name: 'Mamaearth Face Wash', sub: 'Skin' },
      { name: "Pond's Cold Cream", sub: 'Skin' },
      { name: "Pond's Super Light Gel", sub: 'Skin' },
      { name: 'Nivea Soft', sub: 'Skin' },
      { name: 'Nivea Creme', sub: 'Skin' },
      { name: 'Garnier Bright Complete', sub: 'Skin' },
      { name: 'Himalaya Nourishing Cream', sub: 'Skin' },
      { name: 'Boroplus Cream', sub: 'Skin' },
      { name: 'Vaseline Body Lotion', sub: 'Skin' },
      { name: 'Nivea Body Lotion', sub: 'Skin' },
      { name: 'Himalaya Body Lotion', sub: 'Skin' },
      { name: 'Dove Body Lotion', sub: 'Skin' },
      { name: 'Parachute Body Lotion', sub: 'Skin' },
      { name: 'Fogg Deo', sub: 'Deo' },
      { name: 'Nivea Deo', sub: 'Deo' },
      { name: 'Wild Stone Deo', sub: 'Deo' },
      { name: 'Park Avenue Deo', sub: 'Deo' },
      { name: 'Engage Deo', sub: 'Deo' },
      { name: 'Axe Deo', sub: 'Deo' },
      { name: 'Denver Deo', sub: 'Deo' },
      { name: 'Fogg Perfume', sub: 'Deo' },
      { name: 'Denver Perfume', sub: 'Deo' },
      { name: 'Engage Perfume', sub: 'Deo' },
      { name: 'Bella Vita Perfume', sub: 'Deo' },
      { name: 'Yardley Perfume', sub: 'Deo' },
      { name: 'Ponds Dreamflower', sub: 'Powder' },
      { name: 'Nycil Powder', sub: 'Powder' },
      { name: 'Santoor Powder', sub: 'Powder' },
      { name: 'Cinthol Powder', sub: 'Powder' },
      { name: 'Navratna Powder', sub: 'Powder' },
      { name: 'Dettol Hand Wash', sub: 'Soap' },
      { name: 'Lifebuoy Hand Wash', sub: 'Soap' },
      { name: 'Savlon Hand Wash', sub: 'Soap' },
      { name: 'Himalaya Hand Wash', sub: 'Soap' },
      { name: 'Godrej Protekt Hand Wash', sub: 'Soap' },
      { name: 'Dettol Sanitizer', sub: 'Soap' },
      { name: 'Lifebuoy Sanitizer', sub: 'Soap' },
      { name: 'Savlon Sanitizer', sub: 'Soap' },
      { name: 'Himalaya Sanitizer', sub: 'Soap' },
      { name: 'Vaseline Lip Balm', sub: 'Skin' },
      { name: 'Nivea Lip Balm', sub: 'Skin' },
      { name: 'Himalaya Lip Balm', sub: 'Skin' },
      { name: 'Maybelline Baby Lips', sub: 'Skin' },
      { name: 'Cotton Balls', sub: 'Hygiene' },
      { name: 'Cotton Buds', sub: 'Hygiene' },
      { name: 'Cotton Roll', sub: 'Hygiene' },
      { name: 'Wet Wipes', sub: 'Hygiene' },
      { name: 'Facial Tissue', sub: 'Hygiene' },
      { name: 'Whisper Ultra', sub: 'Pad' },
      { name: 'Whisper Choice', sub: 'Pad' },
      { name: 'Stayfree Secure', sub: 'Pad' },
      { name: 'Stayfree XL', sub: 'Pad' },
      { name: 'Sofy Anti Bacteria', sub: 'Pad' },
      { name: 'Sofy XL', sub: 'Pad' },
      { name: 'Kotex Pads', sub: 'Pad' },
      { name: 'Tampax Tampons', sub: 'Pad' },
      { name: 'Sirona Menstrual Cup', sub: 'Pad' },
      { name: 'Whisper Panty Liners', sub: 'Pad' },
      { name: 'Stayfree Panty Liners', sub: 'Pad' },
    ]
  },
  {
    id: 15, name: 'Baby Care', icon: 'Baby',
    image: '/images/baby.png',
    brands: ["Johnson's Baby", 'Himalaya Baby', 'Pampers', 'Huggies', 'MamyPoko', 'Nestlé', 'Aptamil', 'Dexolac', 'Chicco', 'Mee Mee', 'Pigeon', 'Philips Avent', 'Sebamed', 'Babyhug', 'Local'],
    items: [
      { name: 'Lactogen 1', sub: 'Food' },
      { name: 'Lactogen 2', sub: 'Food' },
      { name: 'Lactogen 3', sub: 'Food' },
      { name: 'NAN PRO 1', sub: 'Food' },
      { name: 'NAN PRO 2', sub: 'Food' },
      { name: 'NAN PRO 3', sub: 'Food' },
      { name: 'Aptamil Stage 1', sub: 'Food' },
      { name: 'Aptamil Stage 2', sub: 'Food' },
      { name: 'Aptamil Stage 3', sub: 'Food' },
      { name: 'Dexolac Stage 1', sub: 'Food' },
      { name: 'Dexolac Stage 2', sub: 'Food' },
      { name: 'Dexolac Stage 3', sub: 'Food' },
      { name: 'Cerelac Rice', sub: 'Food' },
      { name: 'Cerelac Wheat', sub: 'Food' },
      { name: 'Cerelac Wheat Apple', sub: 'Food' },
      { name: 'Cerelac Wheat Mixed Fruits', sub: 'Food' },
      { name: 'Cerelac Khichdi', sub: 'Food' },
      { name: 'Cerelac Dal Khichdi', sub: 'Food' },
      { name: 'Farex Baby Food', sub: 'Food' },
      { name: 'Ragi Cereal', sub: 'Food' },
      { name: 'Oats Baby Cereal', sub: 'Food' },
      { name: 'Multigrain Baby Cereal', sub: 'Food' },
      { name: 'Fruit Puree', sub: 'Food' },
      { name: 'Vegetable Puree', sub: 'Food' },
      { name: 'Apple Puree', sub: 'Food' },
      { name: 'Banana Puree', sub: 'Food' },
      { name: 'Pampers New Baby', sub: 'Diaper' },
      { name: 'Pampers Active Baby', sub: 'Diaper' },
      { name: 'Pampers Premium Care', sub: 'Diaper' },
      { name: 'Huggies Wonder Pants', sub: 'Diaper' },
      { name: 'Huggies Complete Comfort', sub: 'Diaper' },
      { name: 'MamyPoko Pants', sub: 'Diaper' },
      { name: 'MamyPoko Extra Absorb', sub: 'Diaper' },
      { name: 'Himalaya Diapers', sub: 'Diaper' },
      { name: 'Little Angel Diapers', sub: 'Diaper' },
      { name: 'Himalaya Baby Wipes', sub: 'Wipe' },
      { name: "Johnson's Baby Wipes", sub: 'Wipe' },
      { name: 'Pampers Baby Wipes', sub: 'Wipe' },
      { name: 'Mee Mee Baby Wipes', sub: 'Wipe' },
      { name: 'Mother Sparsh Baby Wipes', sub: 'Wipe' },
      { name: "Johnson's Baby Soap", sub: 'Soap' },
      { name: 'Himalaya Baby Soap', sub: 'Soap' },
      { name: 'Sebamed Baby Soap', sub: 'Soap' },
      { name: 'Mee Mee Baby Soap', sub: 'Soap' },
      { name: 'Chicco Baby Soap', sub: 'Soap' },
      { name: "Johnson's Baby Shampoo", sub: 'Soap' },
      { name: 'Himalaya Baby Shampoo', sub: 'Soap' },
      { name: 'Sebamed Baby Shampoo', sub: 'Soap' },
      { name: 'Chicco Baby Shampoo', sub: 'Soap' },
      { name: "Johnson's Baby Oil", sub: 'Skin' },
      { name: 'Himalaya Baby Oil', sub: 'Skin' },
      { name: 'Dabur Baby Oil', sub: 'Skin' },
      { name: 'Chicco Baby Oil', sub: 'Skin' },
      { name: "Johnson's Baby Lotion", sub: 'Skin' },
      { name: 'Himalaya Baby Lotion', sub: 'Skin' },
      { name: 'Sebamed Baby Lotion', sub: 'Skin' },
      { name: 'Chicco Baby Lotion', sub: 'Skin' },
      { name: "Johnson's Baby Powder", sub: 'Skin' },
      { name: 'Himalaya Baby Powder', sub: 'Skin' },
      { name: 'Chicco Baby Powder', sub: 'Skin' },
      { name: "Johnson's Baby Cream", sub: 'Skin' },
      { name: 'Himalaya Baby Cream', sub: 'Skin' },
      { name: 'Sebamed Baby Cream', sub: 'Skin' },
      { name: 'Chicco Baby Cream', sub: 'Skin' },
      { name: 'Baby Toothpaste', sub: 'Tool' },
      { name: 'Baby Toothbrush', sub: 'Tool' },
      { name: 'Finger Toothbrush', sub: 'Tool' },
      { name: 'Training Toothbrush', sub: 'Tool' },
      { name: 'Philips Avent Bottle', sub: 'Tool' },
      { name: 'Pigeon Feeding Bottle', sub: 'Tool' },
      { name: 'Mee Mee Feeding Bottle', sub: 'Tool' },
      { name: 'Chicco Feeding Bottle', sub: 'Tool' },
      { name: 'Babyhug Feeding Bottle', sub: 'Tool' },
      { name: 'Feeding Spoon', sub: 'Tool' },
      { name: 'Feeding Bowl', sub: 'Tool' },
      { name: 'Sipper Cup', sub: 'Tool' },
      { name: 'Straw Cup', sub: 'Tool' },
      { name: 'Baby Training Cup', sub: 'Tool' },
      { name: 'Bottle Cleaner Brush', sub: 'Tool' },
      { name: 'Bottle Sterilizer', sub: 'Tool' },
      { name: 'Silicone Pacifier', sub: 'Tool' },
      { name: 'Orthodontic Pacifier', sub: 'Tool' },
      { name: 'Water Filled Teether', sub: 'Tool' },
      { name: 'Silicone Teether', sub: 'Tool' },
      { name: 'Wooden Teether', sub: 'Tool' },
      { name: 'Baby Bib', sub: 'Tool' },
      { name: 'Baby Plate', sub: 'Tool' },
      { name: 'Baby Food Container', sub: 'Tool' },
      { name: 'Snack Box', sub: 'Tool' },
      { name: 'Food Storage Cups', sub: 'Tool' },
      { name: 'Baby Laundry Detergent', sub: 'Soap' },
      { name: 'Baby Fabric Softener', sub: 'Soap' },
      { name: 'Digital Thermometer', sub: 'Health' },
      { name: 'Baby Nail Cutter', sub: 'Health' },
      { name: 'Baby Comb', sub: 'Health' },
      { name: 'Baby Hair Brush', sub: 'Health' },
      { name: 'Nasal Aspirator', sub: 'Health' },
      { name: 'Baby Medicine Dropper', sub: 'Health' },
      { name: 'Baby Blanket', sub: 'Cloth' },
      { name: 'Baby Towel', sub: 'Cloth' },
      { name: 'Baby Pillow', sub: 'Cloth' },
      { name: 'Baby Mosquito Net', sub: 'Cloth' },
      { name: 'Baby Cap', sub: 'Cloth' },
      { name: 'Baby Mittens', sub: 'Cloth' },
      { name: 'Baby Socks', sub: 'Cloth' }
    ]
  },
  {
    id: 16, name: 'Household Needs', icon: 'Home',
    image: '/images/household.png',
    brands: ['Origami', 'Bella', 'Selpak', 'Good Knight', 'All Out', 'Mortein', 'HIT', 'Philips', 'Havells', 'Wipro', 'Syska', 'Eveready', 'Duracell', 'Fevicol', 'Feviquick', 'M-Seal', 'Local'],
    items: [
      { name: 'Small Garbage Bags', sub: 'Bag' },
      { name: 'Medium Garbage Bags', sub: 'Bag' },
      { name: 'Large Garbage Bags', sub: 'Bag' },
      { name: 'Extra Large Garbage Bags', sub: 'Bag' },
      { name: 'Biodegradable Garbage Bags', sub: 'Bag' },
      { name: 'Black Garbage Bags', sub: 'Bag' },
      { name: 'Drawstring Garbage Bags', sub: 'Bag' },
      { name: 'Facial Tissue Box', sub: 'Paper' },
      { name: 'Pocket Tissue Pack', sub: 'Paper' },
      { name: 'Soft Facial Tissue', sub: 'Paper' },
      { name: 'Toilet Paper Roll', sub: 'Paper' },
      { name: 'Premium Toilet Roll', sub: 'Paper' },
      { name: 'Kitchen Paper Towels', sub: 'Paper' },
      { name: 'Jumbo Kitchen Roll', sub: 'Paper' },
      { name: 'Paper Napkins', sub: 'Paper' },
      { name: 'Printed Paper Napkins', sub: 'Paper' },
      { name: 'Paper Plates', sub: 'Paper' },
      { name: 'Silver Laminated Plates', sub: 'Paper' },
      { name: 'Areca Leaf Plates', sub: 'Paper' },
      { name: 'Paper Cups', sub: 'Paper' },
      { name: 'Plastic Cups', sub: 'Plastic' },
      { name: 'Paper Bowls', sub: 'Paper' },
      { name: 'Disposable Bowls', sub: 'Paper' },
      { name: 'Plastic Spoons', sub: 'Plastic' },
      { name: 'Plastic Forks', sub: 'Plastic' },
      { name: 'Plastic Knives', sub: 'Plastic' },
      { name: 'Disposable Glasses', sub: 'Plastic' },
      { name: 'Disposable Lunch Boxes', sub: 'Plastic' },
      { name: 'Food Containers', sub: 'Plastic' },
      { name: 'Aluminium Foil', sub: 'Foil' },
      { name: 'Cling Wrap', sub: 'Foil' },
      { name: 'Butter Paper', sub: 'Foil' },
      { name: 'Zip Lock Bags', sub: 'Plastic' },
      { name: 'Food Storage Containers', sub: 'Plastic' },
      { name: 'Airtight Containers', sub: 'Plastic' },
      { name: 'Plastic Storage Boxes', sub: 'Plastic' },
      { name: 'Steel Storage Containers', sub: 'Metal' },
      { name: 'Match Box', sub: 'Misc' },
      { name: 'Gas Lighter', sub: 'Misc' },
      { name: 'Candle', sub: 'Misc' },
      { name: 'Tea Light Candle', sub: 'Misc' },
      { name: 'Emergency Candle', sub: 'Misc' },
      { name: 'Good Knight Liquid Refill', sub: 'Misc' },
      { name: 'Good Knight Machine', sub: 'Misc' },
      { name: 'All Out Liquid Refill', sub: 'Misc' },
      { name: 'All Out Machine', sub: 'Misc' },
      { name: 'Mortein Liquid', sub: 'Misc' },
      { name: 'Mortein Coil', sub: 'Misc' },
      { name: 'Good Knight Coil', sub: 'Misc' },
      { name: 'HIT Mosquito Spray', sub: 'Misc' },
      { name: 'Mosquito Bat', sub: 'Misc' },
      { name: 'Mosquito Net', sub: 'Misc' },
      { name: 'Odonil Air Freshener', sub: 'Misc' },
      { name: 'Air Wick Freshener', sub: 'Misc' },
      { name: 'Godrej Aer', sub: 'Misc' },
      { name: 'Room Spray', sub: 'Misc' },
      { name: 'Bathroom Freshener', sub: 'Misc' },
      { name: 'LED Bulb 5W', sub: 'Misc' },
      { name: 'LED Bulb 9W', sub: 'Misc' },
      { name: 'LED Bulb 12W', sub: 'Misc' },
      { name: 'LED Bulb 15W', sub: 'Misc' },
      { name: 'LED Tube Light', sub: 'Misc' },
      { name: 'Tube Light Starter', sub: 'Misc' },
      { name: 'AA Batteries', sub: 'Misc' },
      { name: 'AAA Batteries', sub: 'Misc' },
      { name: '9V Battery', sub: 'Misc' },
      { name: 'Button Cell Battery', sub: 'Misc' },
      { name: '3 Pin Extension Board', sub: 'Misc' },
      { name: '4 Socket Extension Board', sub: 'Misc' },
      { name: 'Spike Guard', sub: 'Misc' },
      { name: 'Cloth Clips Plastic', sub: 'Misc' },
      { name: 'Wooden Cloth Clips', sub: 'Misc' },
      { name: 'Clothes Hangers', sub: 'Misc' },
      { name: 'Laundry Basket', sub: 'Misc' },
      { name: 'Clothes Drying Rope', sub: 'Misc' },
      { name: 'Bucket', sub: 'Plastic' },
      { name: 'Mug', sub: 'Plastic' },
      { name: 'Plastic Tub', sub: 'Plastic' },
      { name: 'Water Can', sub: 'Plastic' },
      { name: 'Storage Drum', sub: 'Plastic' },
      { name: 'Floor Wiper', sub: 'Misc' },
      { name: 'Dust Bin Small', sub: 'Plastic' },
      { name: 'Dust Bin Large', sub: 'Plastic' },
      { name: 'Adhesive Tape', sub: 'Misc' },
      { name: 'Double Sided Tape', sub: 'Misc' },
      { name: 'Super Glue', sub: 'Misc' },
      { name: 'Fevicol', sub: 'Misc' },
      { name: 'Feviquick', sub: 'Misc' },
      { name: 'Rope', sub: 'Misc' },
      { name: 'Nylon Rope', sub: 'Misc' },
      { name: 'Scissors', sub: 'Misc' },
      { name: 'Ball Pens', sub: 'Misc' },
      { name: 'Pencils', sub: 'Misc' },
      { name: 'Erasers', sub: 'Misc' },
      { name: 'Sharpeners', sub: 'Misc' },
      { name: 'Notebook', sub: 'Misc' },
      { name: 'Sticky Notes', sub: 'Misc' },
      { name: 'Marker Pen', sub: 'Misc' },
      { name: 'Permanent Marker', sub: 'Misc' },
      { name: 'Agarbatti', sub: 'Misc' },
      { name: 'Dhoop Sticks', sub: 'Misc' },
      { name: 'Camphor', sub: 'Misc' },
      { name: 'Cotton Wicks', sub: 'Misc' },
      { name: 'Pooja Oil', sub: 'Misc' },
      { name: 'Kumkum', sub: 'Misc' },
      { name: 'Turmeric Powder (Pooja)', sub: 'Misc' },
      { name: 'Match Box (Pooja)', sub: 'Misc' },
      { name: 'Steel Scrubber', sub: 'Misc' },
      { name: 'Coconut Scrubber', sub: 'Misc' },
      { name: 'Dish Cloth', sub: 'Misc' },
      { name: 'Kitchen Sponge', sub: 'Misc' },
      { name: 'Bottle Brush', sub: 'Misc' },
      { name: 'Vegetable Peeler', sub: 'Misc' },
      { name: 'Kitchen Knife', sub: 'Misc' },
      { name: 'Chopping Board', sub: 'Misc' }
    ]
  }
];

async function seed() {
  const connection = await mysql.createConnection({
    host: process.env.DB_HOST || 'localhost',
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '',
    database: process.env.DB_NAME || 'N2D'
  });

  try {
    // Ensure tables exist before inserting
    await connection.query(`
      CREATE TABLE IF NOT EXISTS categories (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL UNIQUE,
        icon VARCHAR(100) DEFAULT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await connection.query(`
      CREATE TABLE IF NOT EXISTS brands (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(255) NOT NULL UNIQUE
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    await connection.query(`
      CREATE TABLE IF NOT EXISTS product_images (
        id INT PRIMARY KEY AUTO_INCREMENT,
        product_id INT NOT NULL,
        image_url TEXT,
        is_primary BOOLEAN DEFAULT FALSE
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    `);

    // Ensure products table has required grocery columns
    const columns = [
      'category_id INT',
      'brand_id INT',
      'mrp DECIMAL(10,2)',
      'selling_price DECIMAL(10,2)',
      'weight VARCHAR(100)',
      'image_url TEXT',
      'price DECIMAL(10,2)',
      'stock INT DEFAULT 50',
      'category VARCHAR(255)'
    ];

    for (const col of columns) {
      try {
        await connection.query(`ALTER TABLE products ADD COLUMN ${col}`);
      } catch (colErr) {
        // Column already exists, ignore
      }
    }



    for (const cat of categoriesData) {
      console.log(`Inserting Category ${cat.id}: ${cat.name}...`);
      await connection.query("INSERT IGNORE INTO categories (id, name, icon) VALUES (?, ?, ?)", [cat.id, cat.name, cat.icon]);


      for (const b of cat.brands) {
        await connection.query('INSERT IGNORE INTO brands (name) VALUES (?)', [b]);
      }

      let count = 0;
      for (const item of cat.items) {
        let brandName = cat.brands.find(b => item.name.includes(b));
        if (!brandName) brandName = cat.brands[Math.floor(Math.random() * cat.brands.length)];
        
        const [brandRows] = await connection.query('SELECT id FROM brands WHERE name = ?', [brandName]);
        const brandId = brandRows[0].id;

        let weight = '1 pc';
        let mrp = Math.floor(Math.random() * 100) + 30; 
        
        if (cat.id === 12) { // Meat
          weight = '500 g';
          mrp = Math.floor(Math.random() * 500) + 200;
        } else if (cat.id === 13) { // Cleaning
          if (item.sub === 'Powder' || item.sub === 'Liquid') {
            weight = '1 L/kg';
            mrp = Math.floor(Math.random() * 300) + 100;
          } else {
            weight = '1 pc';
          }
        } else if (cat.id === 14) { // Personal
          if (item.sub === 'Shampoo' || item.sub === 'Skin') {
            weight = '200 ml';
            mrp = Math.floor(Math.random() * 300) + 50;
          } else if (item.sub === 'Soap') {
            weight = '100 g';
            mrp = Math.floor(Math.random() * 50) + 20;
          }
        } else if (cat.id === 15) { // Baby
          if (item.sub === 'Food') {
            weight = '400 g';
            mrp = Math.floor(Math.random() * 400) + 200;
          }
        }

        let selling = Math.floor(mrp * (Math.random() * 0.2 + 0.7));

        const [result] = await connection.query(`
          INSERT INTO products (category_id, brand_id, name, weight, mrp, selling_price, stock) 
          VALUES (?, ?, ?, ?, ?, ?, ?)
        `, [cat.id, brandId, item.name, weight, mrp, selling, 50]); 
        
        await connection.query(`
          INSERT INTO product_images (product_id, image_url, is_primary) 
          VALUES (?, ?, TRUE)
        `, [result.insertId, cat.image]);
        
        count++;
      }
      console.log(`Successfully seeded ${count} items for ${cat.name}!`);
    }

  } catch (err) {
    console.error('Error seeding final categories:', err);
  } finally {
    await connection.end();
  }
}

seed();
